
# global params
# appRevision: ""
# targetRevision: ""
# gitopsNamespace: ""
# gitRepo: ""
disableAutoSync: "yes"
# overrideTenants: "no"

# override to create a maintenance message
maintenanceMessage: ""

tenantGitopsInstances: 1

# For disconnected clusters
enableDisconnected: "false"

operators:
- name: namespace-configuration-operator
  disconnectedSource: "cs-community-operator-index"
- name: descheduler
  disconnectedSource: "cs-redhat-operator-index"
- name: vertical-pod-autoscaler
  disconnectedSource: "cs-redhat-operator-index"
- name: keepalived-operator
  disconnectedSource: "cs-community-operator-index"
- name: certmanager-operator
  disconnectedSource: "cs-redhat-operator-index"
- name: istio-operator
  disconnectedSource: "cs-redhat-operator-index"
# - name: gitops-operator
#   disconnectedSource: "cs-redhat-operator-index"
- name: compliance-operator
  disconnectedSource: "cs-redhat-operator-index"
- name: local-storage-operator
  disconnectedSource: "cs-redhat-operator-index"
- name: lvms-operator
  disconnectedSource: "cs-redhat-operator-index"
- name: kargo
  namespace: kargo

clusterComponents:
- name: user-sandbox
- name: keepalived-config
- name: openshift-console-plugin
- name: external-dns
  namespace: "external-dns"
- name: certmanager-config
- name: istio-config

# enable this for gitops cluster updates!
# - name: cluster-version
#   disableFinalizers: "yes" # needs this otherwise clusterversion would be deleted
